### ISSUE TITLE
ECMA Members analysis

### ISSUE THREAD

**Issue by septs** [JSCIG/dataset#3]
https://www.ecma-international.org/memento/members.htm

automated analysis and output to json.

**Comment by TechQuery** [comment]
我们作为“中文”兴趣组，区分出**大中华地区**的会员组织比较重要

**Comment by septs** [comment]
> 我们作为“中文”兴趣组，区分出**大中华地区**的会员组织比较重要

我们可以做一份额外的标记数据与他合并

**Comment by septs** [comment]
https://github.com/JSCIG/dataset/blob/b9b051e/members-ecma.json
