### ISSUE TITLE
本组织成员信息优化

### ISSUE THREAD

**Issue by TechQuery** [JSCIG/dataset#4]
- [ ] `company` 建议改为 `organization`，很多开源组织成员不一定全职于一家公司
- [ ] `organization` 建议分析一下 GitHub `@` 所指向的命名空间
- [ ] `location` 建议用 `,` 拆解一下

**Comment by septs** [comment]
这是 github 提供的原始信息
我认为没有必要过度解读

而且 github 在几个字段允许输入任意内容
因此解释的权利取决于使用者

**Comment by TechQuery** [comment]
> 这是 github 提供的原始信息
> 我认为没有必要过度解读

如果原则是“遵照 GitHub”，那字段名最好也一致，这样**类型声明**就可以直接 `Pick` 官方的类型定义了
