### ISSUE TITLE
watchers_count 与实际数据不匹配

### ISSUE THREAD

**Issue by legendecas** [JSCIG/dataset#5]
Refs: https://jscig.github.io/dataset/proposals.json 

看起来数据是和 stargazers_count 重复了。

**Comment by septs** [comment]
https://github.com/JSCIG/dataset/blob/064c15fc113d2a22699ac0d260cb4edb3aa9ff18/src/fetch/proposals.ts#L57-L60

**Comment by septs** [comment]
see https://github.com/KnpLabs/php-github-api/issues/182#issuecomment-56479717

remove the field on proposal record.
